---
- name: "Create directory {{ EXTRACT_VICEDATA_TARGET_DIR }}"
  file:
    path: "{{ EXTRACT_VICEDATA_TARGET_DIR }}"
    state: directory
    mode: '0755'

- name: "Create directory {{ DOWNLOAD_VICEDATA_DIR }}"
  file:
    path: "{{ DOWNLOAD_VICEDATA_DIR }}"
    state: directory
    mode: '0755'
       
- name: Install compiler and vice
  apt:
    pkg:
    - vice
    state: present
  become: true

- name: Download vice-data from S3
  get_url:
    url: https://rodoherty1-vice-data.s3.eu-west-1.amazonaws.com/vice-data.tar.gz 
    validate_certs: no
    dest: '{{ DOWNLOAD_VICEDATA_ARCHIVE }}'

- name: Extract vice-data.tar.gz
  unarchive:
    src: "{{ DOWNLOAD_VICEDATA_ARCHIVE }}"
    dest: "{{ EXTRACT_VICEDATA_TARGET_DIR }}"
    list_files: yes
  register: archive_contents

- name: Copy vice-data contents to /usr/lib/vice
  copy:
    src: "{{ EXTRACT_VICEDATA_TARGET_DIR }}/data/"
    dest: /usr/lib/vice
    remote_src: yes
  become: true

- name: 'Cleanup downloaded archives'
  file: 
    path: '{{ item }}' 
    state: absent
  with_items:
    - '{{ EXTRACT_VICEDATA_TARGET_DIR }}' 
    - '{{ DOWNLOAD_VICEDATA_ARCHIVE }}'
    - '{{ DOWNLOAD_VSCODE_DIR }}'

